apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: muchtodo
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: example
  MONGO_URI: mongodb://root:example@mongodb-service:27017/much_todo_db?authSource=admin&replicaSet=rs0
